name: Invoker

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: ${{ vars.GH_BUILD_WORKFLOW }}
          repo: ${{ vars.GH_BUILD_REPOSITORY }}
          token: ${{ secrets.GH_PAT_TOKEN }}
          ref: main
          inputs: '{"repository_url": "${{ github.repository }}","branch":"${{ github.ref }}", "sha" : "${{ github.sha }}"}'
